"""small fixes in the UserModel

Revision ID: 15c1c2ce9ef6
Revises: 62acdd867968
Create Date: 2026-03-10 16:20:44.597844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c1c2ce9ef6'
down_revision: Union[str, Sequence[str], None] = '62acdd867968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
