"""fixed datetime issue in the CommentModel

Revision ID: 4a91cb0c4205
Revises: bd1d61cb1649
Create Date: 2026-03-13 13:12:36.371812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a91cb0c4205'
down_revision: Union[str, Sequence[str], None] = 'bd1d61cb1649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
