"""fixed typo in OrderStatus, add CANCELED status to the OrderItemStatus

Revision ID: 612dbe0da688
Revises: e5ee11cfd202
Create Date: 2026-03-18 13:06:06.745987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612dbe0da688'
down_revision: Union[str, Sequence[str], None] = 'e5ee11cfd202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE orderitemstatus ADD VALUE 'CANCELED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
