"""add 'orders' and 'order_items' tables

Revision ID: 9cf5c0efea9b
Revises: 0fc9df55b8da
Create Date: 2026-03-14 17:37:47.665450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf5c0efea9b'
down_revision: Union[str, Sequence[str], None] = '0fc9df55b8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
