"""add status field to the OrderItemModel

Revision ID: e5ee11cfd202
Revises: 10b69bb6f1d7
Create Date: 2026-03-17 20:50:34.945269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5ee11cfd202'
down_revision: Union[str, Sequence[str], None] = '10b69bb6f1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    order_status = postgresql.ENUM(
        'PENDING', 'PAID', 'PARTIALLY_PAID', 'CANCELED', 'COMPLETED',
        name='orderstatus'
    )
    order_status.create(op.get_bind())

    order_item_status = postgresql.ENUM('PENDING', 'PAID', name='orderitemstatus')
    order_item_status.create(op.get_bind())

    op.add_column('order_items',
        sa.Column('status', sa.Enum('PENDING', 'PAID', name='orderitemstatus'),
        nullable=False,
        server_default='PENDING')
    )

    op.execute("""
        ALTER TABLE orders 
        ALTER COLUMN status TYPE orderstatus 
        USING (
            CASE 
                WHEN status = 'completed' THEN 'PAID'::orderstatus
                WHEN status = 'created' THEN 'PENDING'::orderstatus
                ELSE status::orderstatus
            END
        )
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PAID', 'PARTIALLY_PAID', 'CANCELED', name='orderstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
